---
- name: Determine undercloud and allocate inventory
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/shift_stack_vars.yaml
  tasks:
    - name: Add undercloud host to inventory for each cluster to be created
      add_host:
        name: "undercloud-{{ item }}"
        group: underclouds
        ansible_host: "{{ undercloud_host }}"
        ansible_connection: "ssh"
        ansible_user: "stack"
      with_sequence: "start=1 count={{ ocp_cluster_count }} format=%04u"

- hosts: underclouds
  gather_facts: true
  vars_files:
    - vars/shift_stack_vars.yaml
  tasks:
  - name: Get Binaries
    include_tasks: tasks/get_ocp_binaries.yml
    run_once: true

  - name: create flavors
    include_tasks: tasks/create_flavors.yml
    run_once: true

  - name: set masquerade rule
    include_tasks: tasks/set_masquerade.yml
    run_once: true
    when: set_masquerade == true

  - name: create openshift cluster(s)
    include_tasks: tasks/install_ocp_cluster.yml

  - block:
      - name: create ocp infra nodes
        include_tasks: tasks/create_ocp_infra_nodes.yml
    environment:
      KUBECONFIG: /home/stack/ocp_clusters/{{ ocp_cluster_name }}/auth/kubeconfig
