---
- name: Get output of bulk introspection status and store as yaml
  shell: |
       source ~/stackrc
       {% if osp_release|int < 13 %}
       openstack baremetal introspection bulk status -f yaml
       {% else %}
       openstack baremetal introspection list -f yaml
       {% endif %}
  changed_when: false
  register: bulk_status

# Extract introspected nodes to yaml
- name: set fact for introspected nodes
  set_fact:
      introspected_nodes: '{{ bulk_status.stdout | from_yaml }}'

# Construct list of UUID's of nodes failing introspection
- name: set fact for introspection failed UUIDs
  set_fact:
      failed_nodes_uuids: "{{ (failed_nodes_uuids | default([]) ) + [ item[uuid_field_name] ] }}"
  with_items: "{{ introspected_nodes | default([]) }}"
  vars:
      - osp_version: "{{ osp_release }}"
      - uuid_field_name: "{{ ( osp_version|int < 13) | ternary('Node UUID', 'UUID') }}"
      - finished_condition:  "{{ item.get('Error') | ternary( True, (osp_version|int < 13) | ternary(item.get('Finished') == false, item.get('Finished at') is none )) }}"
  when:
      - finished_condition
  tags:
      - skip_ansible_lint

- name: get ipmi addr of failed nodes
  shell: |
    source ~/stackrc
    openstack baremetal node show {{ item }} --fields driver_info -f json | jq '.driver_info.ipmi_address'
  with_items: "{{ failed_nodes_uuids | default([]) }}"
  register: failed_nodes_ipmi_addr

- name: print the ipmi addr of failed nodes
  debug:
    msg: "{{ item.stdout }}"
  with_items: "{{ failed_nodes_ipmi_addr.results }}"
  ignore_errors: yes

# TODO for external labs
- name: get the machine type of introspection failed nodes
  set_fact:
    failed_nodes_machine_type: "{{ failed_nodes_machine_type|default([]) + [(type != '1029u')|ternary(type, (item.stdout.replace('mgmt-', '').replace('\"', '') in tn10rt) | ternary('1029utn10rt', '1029utrtp')) ] }}"
  vars:
      type: "{{ (lab_name == 'scale') | ternary(item.stdout.split('.')[0].split('-')[4], item.stdout.split('.')[0].split('-')[3]) }}"
  with_items: "{{ failed_nodes_ipmi_addr.results }}"

- name: set machine count of failed nodes
  set_fact:
    failed_nodes_machine_count: {}

- name: get machine count of failed nodes
  set_fact:
    failed_nodes_machine_count: "{{ failed_nodes_machine_count | combine({item: (item in failed_nodes_machine_count)|ternary(failed_nodes_machine_count[item], 0)|int + 1 }, recursive=True) }}"
  with_items: "{{ failed_nodes_machine_type }}"
  when: failed_nodes_machine_type is defined

- name: print the machine count of failed nodes
  debug:
    var: failed_nodes_machine_count
  when: failed_nodes_machine_type is defined

- name: power off the failed nodes
  shell: |
    source ~/stackrc
    openstack baremetal node power off {{ item }}
  with_items: "{{ failed_nodes_uuids | default([]) }}"
  changed_when: false
  ignore_errors: true

- name: move to manage and delete failed nodes
  shell: |
      source ~/stackrc
      openstack baremetal node manage {{ item }}
      openstack baremetal node delete {{ item }}
  with_items: "{{ failed_nodes_uuids | default([]) }}"
  changed_when: false
  ignore_errors: true

- name: get nodes in manageable state
  shell: |
      source ~/stackrc
      openstack baremetal node list | grep -i manageable | cut -d "|" -f 2
  register: manageable_nodes
  changed_when: false

- name: set provision state of all nodes to available
  shell: |
      source ~/stackrc;
      openstack baremetal node provide {{ item }};
  with_items: "{{ manageable_nodes.stdout_lines | default([]) }}"
  changed_when: false
  register: prov_state
  until: prov_state is succeeded
  retries: 3
  delay: 30

