---
- name: Run openshift-installer destroy cluster
  shell: |
    ./openshift-install --log-level=debug destroy cluster --dir=/home/stack/ocp_clusters/{{ osp_project_name }}/ > /home/stack/ocp_clusters/{{ osp_project_name }}/ocp_destroy.log 2>&1
  args:
    chdir: /home/stack/
  ignore_errors: true

- name: Delete floating ips
  shell: |
    source /home/stack/overcloudrc
    for i in $(openstack floating ip list --project {{ osp_project_name }} -c ID -f value); do openstack floating ip delete $i; done

- name: Delete security groups
  shell: |
    source /home/stack/overcloudrc
    for i in $(openstack security group list --project {{ osp_project_name }} -c ID -f value); do openstack security group delete $i; done

- name: Delete shiftstack project
  os_project:
    cloud: "overcloud"
    state: absent
    name: "{{ osp_project_name }}"
    domain: default

- name: Delete shiftstack user
  os_user:
    cloud: "overcloud"
    state: absent
    name: "{{ osp_user_name }}"
    domain: default

- name: remove ocp_clusters directory
  file:
    path: /home/stack/ocp_clusters/{{ ocp_cluster_name }}
    state: absent
  ignore_errors: true

- name: Remove DNS detail in etc/hosts
  blockinfile:
    backup: true
    path: "/etc/hosts"
    marker: "# {mark} {{ ocp_cluster_name }} OCP CLUSTER MANAGED BLOCK"
  become: yes
  become_user: root
  throttle: 1

- name: Remove cloud parameters
  blockinfile:
    dest: "/home/stack/clouds.yaml"
    marker: "# {mark} {{ ocp_cluster_name }} OCP CLUSTER MANAGED BLOCK"
  throttle: 1
  when: ansible_distribution_major_version <= '8'

- name: Remove cloud parameters
  blockinfile:
    dest: "/home/stack/.config/openstack/clouds.yaml"
    marker: "# {mark} {{ ocp_cluster_name }} OCP CLUSTER MANAGED BLOCK"
  throttle: 1
  when: ansible_distribution_major_version > '8'
