---
- name: import shift_stack_vars data
  include_vars:
    dir: "{{ playbook_dir }}/vars"
    files_matching: shift_stack_vars.yaml

- name: Get Binaries
  block:
  - name: Set url for installer
    set_fact:
      ocp_installer_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/
    when: ocp_dev_preview == false

  - name: Set url for installer
    set_fact:
      ocp_installer_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview/
    when: ocp_dev_preview

  - name: Get the latest installer
    get_url:
      validate_certs: no
      force: true
      url: "{{ ocp_installer_url }}{{ ocp_release }}/openshift-install-linux.tar.gz"
      dest: /home/stack/openshift-install-linux.tar.gz

  - name: Untar installer
    unarchive:
      src: /home/stack/openshift-install-linux.tar.gz
      dest: /home/stack/
      remote_src: yes

  - name: Get the ocp client
    get_url:
      validate_certs: no
      force: true
      url: "{{ ocp_installer_url }}{{ ocp_release }}/openshift-client-linux.tar.gz"
      dest: /home/stack/openshift-client-linux.tar.gz

  - name: Untar ocp client
    unarchive:
      src: /home/stack/openshift-client-linux.tar.gz
      dest: /home/stack/
      remote_src: yes
      mode: 0700

  - name: Copy oc to bin
    become: true
    shell: |
      cp /home/stack/oc /usr/local/bin
      cp /home/stack/kubectl /usr/local/bin
      chmod a+x /usr/local/bin/oc
      chmod a+x /usr/local/bin/kubectl

