---
- name: using introspection data to set root device
  shell: |
    source ~/stackrc
    openstack baremetal introspection data save "{{ item }}" | jq '.inventory.disks[0]["model"]'
  register: model
  with_items:
    - "{{ total_nodes.stdout_lines }}"

- name: set root hints based on model (740XD G-CL)
  shell: |
    source ~/stackrc
    openstack baremetal node set "{{ item[0] }}" --property root_device='{"model": {{ item[1].stdout_lines[0] }} }'
  with_together:
    - "{{ total_nodes.stdout_lines }}"
    - "{{ model.results }}"
