---
- name: using introspection data to set root device
  shell: |
    source ~/stackrc
    if [[ $(openstack baremetal introspection data save "{{ item }}" |jq '.inventory.disks[] | select(.vendor == "ATA" ) | .serial') ]]; then
      echo $(openstack baremetal introspection data save "{{ item }}" |jq '.inventory.disks[] | select(.vendor == "ATA" ) | .serial' | head -n 1)
    else
      echo $(openstack baremetal introspection data save "{{ item }}" | jq '.inventory.disks[0]["serial"]')
    fi
  register: serial
  with_items:
    - "{{ total_nodes.stdout_lines }}"

- name: set root hints based on model
  shell: |
    source ~/stackrc
    openstack baremetal node set "{{ item[0] }}" --property root_device='{"serial": {{ item[1].stdout_lines[0] }} }'
  with_together:
    - "{{ total_nodes.stdout_lines }}"
    - "{{ serial.results }}"
