- name: get node UUIDs
  shell: |
    source ~/stackrc
    openstack baremetal node list --format value -c UUID
  register: node_uuid

- name: get the node fqdn list
  shell: |
    source ~/stackrc
    openstack baremetal node show {{ item }} --fields driver_info -f json | jq '.driver_info.ipmi_address'
  register: node_fqdn
  loop: "{{ node_uuid.stdout_lines|flatten(levels=1) }}"

- name: populate uuid type map
  set_fact:
    uuid_type_map: "{{ uuid_type_map|default({}) | combine ( {item.0 : type}) }}"
  vars:
    tn10rt: "{{ hostvars['localhost']['tn10rt'] }}"
    type1: "{{ (lab_name == 'scale') | ternary(item.1.stdout.split('.')[0].split('-')[4], item.1.stdout.split('.')[0].split('-')[3]) }}"
    type: "{{ (type1 != '1029u') | ternary(type1, (item.1.stdout.replace('mgmt-', '').replace('\"', '') in tn10rt) | ternary('1029utn10rt', '1029utrtp')) }}"
  with_together:
    - "{{ node_uuid.stdout_lines }}"
    - "{{ node_fqdn.results }}"

- name: setting profile for node type (OSP < 17)
  shell: |
    source ~/stackrc
    openstack baremetal node set {{ item.key }} --property capabilities=profile:baremetal{{ item.value }},cpu_vt:true,cpu_hugepages:true,boot_option:local,cpu_txt:true,cpu_aes:true,cpu_hugepages_1g:true,boot_mode:{{ boot_mode }}
  loop: "{{ uuid_type_map|dict2items }}"
  when: osp_release|int < 17

- name: setting profile for node type (OSP 17)
  shell: |
    source ~/stackrc
    openstack baremetal node set {{ item.key }} --property capabilities=cpu_vt:true,cpu_hugepages:true,boot_option:local,cpu_txt:true,cpu_aes:true,cpu_hugepages_1g:true,boot_mode:{{ boot_mode }}
  loop: "{{ uuid_type_map|dict2items }}"
  when: osp_release|int == 17
