---
- name: get the node uuids
  shell: |
    source ~/stackrc
    openstack baremetal node list -f value -c UUID
  register: node_uuids

- name: using introspection data to set root device
  shell: |
    source ~/stackrc
    openstack baremetal introspection data save "{{ node_uuids.stdout_lines[0] }}" | jq '.inventory.disks[0]["model"]'
  register: model

- name: set root hints based on model (740XD G-CL)
  shell: |
    source ~/stackrc
    openstack baremetal node set "{{ item }}" --property root_device='{"model": {{ model.stdout }}}'
  with_items: "{{ node_uuids.stdout_lines }}"
